import type { Opportunity } from "@/types";

export const OPPORTUNITIES: Opportunity[] = [
  {
    slug: "it-sales-representative",
    title: "IT Sales Representative",
    category: "Business Development",
    status: "open",
    location: "Sri Lanka — remote/field",
    engagementType: "Commission-based / referral opportunity",
    overview:
      "Identify businesses that could benefit from technology solutions and introduce them to Kuluwa.digital through our official enquiry process.",
    responsibilities: [
      "Build relationships with local businesses",
      "Introduce genuine leads through the official process",
      "Follow up professionally with prospects",
      "Maintain accurate records of introductions made",
    ],
    required: ["Strong communication skills", "Basic understanding of business needs", "Reliability and professionalism"],
    preferred: ["Existing local business network", "Prior sales or business-development experience"],
    experience: "No formal minimum — assessed individually based on communication ability and network quality.",
    communication: "Communication expectations and reporting cadence are agreed during onboarding.",
    compensation:
      "Commission-based, tied to projects that are successfully signed and paid for. Exact terms are confirmed in a written agreement before any work begins.",
  },
  {
    slug: "business-development-representative",
    title: "Business Development Representative",
    category: "Business Development",
    status: "open",
    location: "Sri Lanka — remote/field",
    engagementType: "Contract or commission-based",
    overview:
      "Develop relationships with organisations and identify structured project opportunities beyond one-off introductions.",
    responsibilities: [
      "Research and approach target organisations",
      "Qualify project opportunities",
      "Coordinate with the Kuluwa team on proposals",
    ],
    required: ["Professional communication and negotiation skills"],
    preferred: ["B2B sales experience", "CRM tool familiarity"],
    experience: "1+ years in a business-development or sales role preferred, not mandatory.",
    communication: "Regular check-ins with the Kuluwa team; specifics agreed at onboarding.",
    compensation: "Structure depends on arrangement (contract retainer, commission, or hybrid) — confirmed individually.",
  },
  {
    slug: "technology-consultant",
    title: "Technology Consultant",
    category: "Consulting",
    status: "limited",
    location: "Sri Lanka — remote/hybrid",
    engagementType: "Contract, project-based",
    overview: "Advise prospective clients on suitable technology approaches and support early-stage scoping conversations.",
    responsibilities: ["Join discovery calls with prospective clients", "Advise on technical feasibility", "Support scoping and proposal preparation"],
    required: ["Solid understanding of software/technology delivery", "Strong client-facing communication"],
    preferred: ["Experience across multiple technology domains"],
    experience: "3+ years in technology, product, or consulting roles preferred.",
    communication: "Engaged per project as needed.",
    compensation: "Project-based fee, agreed per engagement.",
  },
  {
    slug: "business-analyst",
    title: "Business Analyst",
    category: "Consulting",
    status: "open",
    location: "Sri Lanka — remote/hybrid",
    engagementType: "Contract or project-based",
    overview: "Translate client business problems into clear requirements the development team can act on.",
    responsibilities: ["Run requirement-gathering sessions", "Document functional requirements", "Bridge communication between clients and developers"],
    required: ["Structured, analytical thinking", "Clear written and verbal communication"],
    preferred: ["Prior business analysis experience"],
    experience: "1–3 years preferred; entry-level candidates with strong aptitude considered.",
    communication: "Regular collaboration with the project team during active engagements.",
    compensation: "Contract or project-based fee, agreed individually.",
  },
  {
    slug: "project-coordinator",
    title: "Project Coordinator",
    category: "Delivery",
    status: "open",
    location: "Sri Lanka — remote/hybrid",
    engagementType: "Contract or part-time",
    overview: "Keep projects organised — tracking timelines, tasks and communication between the team and the client.",
    responsibilities: ["Track project timelines and deliverables", "Coordinate between developers and clients", "Flag risks and delays early"],
    required: ["Strong organisational skills"],
    preferred: ["Experience with project-management tools"],
    experience: "Open to candidates with demonstrable organisational ability.",
    communication: "Daily/weekly check-ins depending on active project load.",
    compensation: "Contract or part-time arrangement, agreed individually.",
  },
  {
    slug: "web-developer",
    title: "Web Developer",
    category: "Technical",
    status: "open",
    location: "Sri Lanka — remote",
    engagementType: "Contract or project-based",
    overview: "Build and maintain websites and web applications as part of project teams.",
    responsibilities: ["Develop responsive websites and web apps", "Collaborate with designers and other developers", "Write maintainable, tested code"],
    required: ["Practical experience with modern web development"],
    preferred: ["Experience with modern JavaScript frameworks", "Backend/API experience"],
    experience: "Junior to senior levels considered — role and rate matched to experience.",
    communication: "Team collaboration through standard project communication channels.",
    compensation: "Project-based or contract rate, agreed based on experience and scope.",
  },
  {
    slug: "mobile-app-developer",
    title: "Mobile App Developer",
    category: "Technical",
    status: "limited",
    location: "Sri Lanka — remote",
    engagementType: "Contract or project-based",
    overview: "Build Android, iOS or cross-platform mobile applications for client projects.",
    responsibilities: ["Develop mobile applications from design specs", "Integrate with backend services and APIs"],
    required: ["Practical experience building and shipping mobile apps"],
    preferred: ["Cross-platform framework experience"],
    experience: "Mid to senior level preferred for this opening.",
    communication: "Team collaboration through standard project communication channels.",
    compensation: "Project-based or contract rate, agreed based on experience and scope.",
  },
  {
    slug: "ai-developer",
    title: "AI Developer",
    category: "Technical",
    status: "limited",
    location: "Sri Lanka — remote",
    engagementType: "Contract or project-based",
    overview: "Support AI feature development, from prototyping to integration into client products.",
    responsibilities: ["Prototype AI-powered features", "Integrate AI providers/APIs into applications"],
    required: ["Practical experience working with AI/LLM APIs or ML tooling"],
    preferred: ["Experience with production AI integrations"],
    experience: "Mid to senior level preferred.",
    communication: "Team collaboration through standard project communication channels.",
    compensation: "Project-based or contract rate, agreed based on experience and scope.",
  },
  {
    slug: "ui-ux-designer",
    title: "UI/UX Designer",
    category: "Technical",
    status: "open",
    location: "Sri Lanka — remote",
    engagementType: "Contract or project-based",
    overview: "Design interfaces and experiences for client web and mobile products.",
    responsibilities: ["Conduct UX research where relevant", "Wireframe and design interfaces"],
    required: ["Strong portfolio of UI/UX work"],
    preferred: ["Design systems experience"],
    experience: "Junior to senior levels considered.",
    communication: "Team collaboration through standard project communication channels.",
    compensation: "Project-based or contract rate, agreed based on experience and scope.",
  },
  {
    slug: "seo-specialist",
    title: "SEO Specialist",
    category: "Marketing",
    status: "limited",
    location: "Sri Lanka — remote",
    engagementType: "Contract or retainer",
    overview: "Support technical and on-page SEO work for client websites.",
    responsibilities: ["Run SEO audits", "Implement on-page and technical fixes"],
    required: ["Practical, demonstrable SEO experience"],
    preferred: ["Experience with analytics and search console tooling"],
    experience: "1+ years hands-on SEO experience preferred.",
    communication: "Regular reporting cadence agreed per client.",
    compensation: "Retainer or project-based, agreed individually.",
  },
];

export function getOpportunityBySlug(slug: string): Opportunity | undefined {
  return OPPORTUNITIES.find((o) => o.slug === slug);
}
